title: 빅데이터개론2 모듈
description: 이 페이지는 빅데이터개론2의 강의ㄹㄹ 구성하는 모듈에 대한 성렴입니다.
theme: just-the-docs

url: https://ilovedata.github.io/intro_bigdata

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
